### ISSUE TITLE
Compilation breaks on: # Foo\n\n ### Bar \n\n

### ISSUE THREAD

**Issue by SamuelMarks** [mmark-md/mmark#62]
Replication steps (mmark 2.0.40, xml2rfc 2.22.0):
```
$ mmark index.md > index.xml
$ xml2rfc index.xml -o index.html
Error: Unable to parse the XML document: index.xml
 <string>: Line 24: Opening and ending tag mismatch: middle line 17 and
section
 <string>: Line 24: Opening and ending tag mismatch: middle line 17 and
section
 <string>: Line 28: Opening and ending tag mismatch: rfc line 3 and section
 <string>: Line 30: Extra content at the end of the document
```

More info:
https://mailarchive.ietf.org/arch/msg/xml2rfc/OPep-8cpM-NZFqQZzX_whWpU9iw

**Comment by mrkkrp** [comment]
There is no such version of MMark as 2.0.40 :)

**Comment by mrkkrp** [comment]
I don't know why you expect MMark to parse the document between `%%%` separators at the beginning. It only parses YAML, and it should be between `---` separators. The title is also misleading, if I feed `# Foo\n\n ### Bar \n\n` I get this back:

```html
<h1 id="foo">Foo</h1>
<h3 id="bar">Bar</h3>
```

which looks like the expected result to me.

Can you clarify the issue? Otherwise I'd have to close it as non-actionable.

**Comment by SamuelMarks** [comment]
Apologies, got confused, wanted to open an issue here: https://github.com/mmarkdown/mmark
